<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="<?= $this->baseUrl("/public/css/styles.css") ?>" rel="stylesheet">
    
    <link href="<?= $this->baseUrl("/public/images/favicon.png") ?>" type="image/png" rel="icon" />
    <link href="<?= $this->baseUrl("/public/images/appicon.jpg") ?>" rel="apple-touch-icon-precomposed" />
    <meta name="msapplication-square150x150logo" content="<?= $this->baseUrl("/public/images/wintile.png") ?>"/>
    <meta name="msapplication-TileColor" content="#36ab66"/>
        
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
      <div class="clearfix">
        <div class="col-md-6 col-sm-8 col-md-offset-3 col-sm-offset-2">
            <div class="text-center">
                <h1>HUBOT</h1>
                <img src="<?= $this->baseUrl("/public/images/hubert.png") ?>" class="img-responsive" style="display: initial" />
            </div>
            
            <br/>
            <br/>
            <div style="background-color: #FFF; padding: 10px;" id="dialog">
                
            </div>
            <form id="form">
                <div class="input-group">
                    <input name="message" id="message" type="text" class="form-control" placeholder="your message...." autocomplete="off">
                    <div class="input-group-btn">
                      <button class="btn btn-default" type="submit">
                          <i class="glyphicon glyphicon-send"></i>
                      </button>
                    </div>
                </div>
            </form>
        </div>
      </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript">
        var bot_url = "<?= $driver_url ?>";
    </script>
    <script src="<?= $this->baseUrl("/public/js/bot.js") ?>" ></script>
  </body>
</html>